server:
    port: 8012
spring:
    application:
        name: PhotoAppAPIConfigServer
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    force-pull: true
                    password: 404@Error
                    uri: https://github.com/deepankar0522/PhotoAppConfiguration
                    username: deepankar0522
